CREATE TABLE "crashes" (
	"id" text PRIMARY KEY NOT NULL,
	"source" text,
	"severity" integer,
	"start_time" timestamp,
	"end_time" timestamp,
	"start_lat" double precision,
	"start_lng" double precision,
	"end_lat" double precision,
	"end_lng" double precision,
	"distance" double precision,
	"description" text,
	"street" text,
	"city" text,
	"county" text,
	"state" text,
	"zipcode" text,
	"country" text,
	"timezone" text,
	"airport_code" text,
	"weather_timestamp" timestamp,
	"temperature" double precision,
	"wind_chill" double precision,
	"humidity" double precision,
	"pressure" double precision,
	"visibility" double precision,
	"wind_direction" text,
	"wind_speed" double precision,
	"precipitation" double precision,
	"weather_condition" text,
	"amenity" boolean,
	"bump" boolean,
	"crossing" boolean,
	"give_way" boolean,
	"junction" boolean,
	"no_exit" boolean,
	"railway" boolean,
	"roundabout" boolean,
	"station" boolean,
	"stop" boolean,
	"traffic_calming" boolean,
	"traffic_signal" boolean,
	"turning_loop" boolean,
	"sunrise_sunset" text,
	"civil_twilight" text,
	"nautical_twilight" text,
	"astronomical_twilight" text
);
--> statement-breakpoint
CREATE INDEX "crashes_state_lower_city_idx" ON "crashes" USING btree ("state",lower("city"));--> statement-breakpoint
CREATE INDEX "crashes_start_time_idx" ON "crashes" USING btree ("start_time");